SQL_EXAMPLES = [
    # 1. Basic SELECT from PO line table
    "SELECT * FROM PO_LINE_TABLE_DUMMY WHERE LINE_STATUS = 'APPROVED';",

    # 2. Filter and order by ordered amount
    "SELECT PO_NUM, ORDERED_AMOUNT FROM PO_LINE_TABLE_DUMMY WHERE CURRENCY_CODE = 'USD' ORDER BY ORDERED_AMOUNT DESC;",

    # 3. Join PO_LINE and PO_NORM to get supplier info
    """SELECT PL.PO_NUM, PL.ITEM_DESCRIPTION, PN.SUPPLIER_NAME
       FROM PO_LINE_TABLE_DUMMY PL
       JOIN PO_NORM_TABLE_DUMMY PN ON PL.PO_NUM = PN.PO_NUM;""",

    # 4. Filter JOIN with PO status
    """SELECT PN.PO_NUM, PN.REQUISTION_NO, PL.LINE_STATUS
       FROM PO_NORM_TABLE_DUMMY PN
       JOIN PO_LINE_TABLE_DUMMY PL ON PN.PO_NUM = PL.PO_NUM
       WHERE PL.LINE_STATUS = 'PENDING';""",

    # 5. Join PR and PO_NORM table (with correct column)
    """SELECT PR.REQUISTION_NO, PR.DEPARTMENT, PR.REQUISITION_STATUS, PN.PO_NUM
       FROM PR_DATA_DUMMY PR
       JOIN PO_NORM_TABLE_DUMMY PN ON PR.REQUISTION_NO = PN.REQUISITION_NUMBER;""",

    # 6. Subquery: high-value POs
    """SELECT PO_NUM, ORDERED_AMOUNT
       FROM PO_LINE_TABLE_DUMMY
       WHERE ORDERED_AMOUNT > (SELECT AVG(ORDERED_AMOUNT) FROM PO_LINE_TABLE_DUMMY);""",

    # 7. CTE: Count of line statuses
    """WITH StatusCount AS (
           SELECT LINE_STATUS, COUNT(*) AS status_count
           FROM PO_LINE_TABLE_DUMMY
           GROUP BY LINE_STATUS
       )
       SELECT * FROM StatusCount WHERE status_count > 2;""",

    # 8. Join PO_LINE with INVOICE and filter by GRN status
    """SELECT PL.PO_NUM, PI.INVOICE_NUM, PI.GRN_STATUS
       FROM PO_LINE_TABLE_DUMMY PL
       JOIN PO_INVOICE_DATA_DUMMY PI ON PL.PO_NUM = PI.PO_NUMBER
       WHERE PI.GRN_STATUS = 'PARTIALLY_RECEIVED';""",

    # 9. Window function to rank top ordered items
    """SELECT PO_NUM, ITEM_DESCRIPTION, ORDERED_AMOUNT,
              RANK() OVER (PARTITION BY CURRENCY_CODE ORDER BY ORDERED_AMOUNT DESC) AS rank_by_currency
       FROM PO_LINE_TABLE_DUMMY;""",

    # 10. Join across all 4 tables using correct columns
    """SELECT PR.REQUISTION_NO, PR.DEPARTMENT, PL.PO_NUM, PI.INVOICE_NUM, PI.GRN_STATUS
       FROM PR_DATA_DUMMY PR
       JOIN PO_NORM_TABLE_DUMMY PN ON PR.REQUISTION_NO = PN.REQUISITION_NUMBER
       JOIN PO_LINE_TABLE_DUMMY PL ON PN.PO_NUM = PL.PO_NUM
       JOIN PO_INVOICE_DATA_DUMMY PI ON PL.PO_NUM = PI.PO_NUMBER
       WHERE PI.GRN_STATUS = 'RECEIVED';"""
    # 11. For date filtering
    """SELECT PO_NUM, ORDERED_AMOUNT
       FROM PO_NORM_TABLE_DUMMY
       WHERE PO_CREATION_DATE > SYSDATE - 30;""",
    # 12. For aggregation
    """SELECT PO_NUM, SUM(ORDERED_AMOUNT) AS total_ordered
       FROM PO_LINE_TABLE_DUMMY
       GROUP BY PO_NUM
       HAVING SUM(ORDERED_AMOUNT) > 10000;""",
    # 13. For complex JOIN with multiple conditions
    """SELECT PL.PO_NUM, PL.ITEM_DESCRIPTION, PN.SUPPLIER_NAME, PI.INVOICE_AMOUNT
       FROM PO_LINE_TABLE_DUMMY PL
       JOIN PO_NORM_TABLE_DUMMY PN ON PL.PO_NUM = PN.PO_NUM
       JOIN PO_INVOICE_DATA_DUMMY PI ON PL.PO_NUM = PI.PO_NUMBER
       WHERE PN.CURRENCY_CODE = 'USD' AND PI.GRN_STATUS = 'RECEIVED';""",
    # 14. For subquery with IN clause
    """SELECT PO_NUM, ORDERED_AMOUNT
       FROM PO_LINE_TABLE_DUMMY
       WHERE PO_NUM IN (SELECT PO_NUM FROM PO_NORM_TABLE_DUMMY WHERE PO_STATUS = 'OPEN');""",
    # 15. For UNION of two SELECT statements
    """SELECT PO_NUM, ORDERED_AMOUNT
       FROM PO_LINE_TABLE_DUMMY
       WHERE LINE_STATUS = 'APPROVED'
    UNION
    SELECT PO_NUM, ORDERED_AMOUNT
       FROM PO_NORM_TABLE_DUMMY
       WHERE PO_STATUS = 'CLOSED';""",
    # 16. For CASE statement in SELECT
    """SELECT PO_NUM, ORDERED_AMOUNT,
              CASE
                  WHEN ORDERED_AMOUNT > 10000 THEN 'High'
                  WHEN ORDERED_AMOUNT BETWEEN 5000 AND 10000 THEN 'Medium'
                  ELSE 'Low'
              END AS order_value
       FROM PO_LINE_TABLE_DUMMY;""",
    # 17. For subquery in FROM clause
    """SELECT PO_NUM, AVG(ORDERED_AMOUNT) AS avg_ordered
       FROM (SELECT PO_NUM, ORDERED_AMOUNT
             FROM PO_LINE_TABLE_DUMMY
             WHERE LINE_STATUS = 'APPROVED')
       GROUP BY PO_NUM;""",
       
]
